services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - "4001:4001"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
