services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container.
      - "4001:4001"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: racing_leaderboards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
