defmodule RacingLeaderboards.Repo.Migrations.PopulateWrc24 do
  use Ecto.Migration

  import Ecto.Query
  import Ecto.Multi

  alias RacingLeaderboards.Cars.Car
  alias RacingLeaderboards.Games
  alias RacingLeaderboards.Circuits.Circuit
  alias RacingLeaderboards.Repo

  def up do
    now = DateTime.utc_now() |> DateTime.truncate(:second)

    game = Games.get_game_by_code!("wrc-24")

    cars_raw = [
      {"Ford Puma Rally1 HYBRID '23", "Rally", "WRC"},
      {"Hyundai i20 N Rally1 HYBRID '23", "Rally", "WRC"},
      {"Toyota GR Yaris Rally1 HYBRID '23", "Rally", "WRC"},
      {"Citroën C3 Rally2", "Rally", "WRC2"},
      {"Ford Fiesta Rally2", "Rally", "WRC2"},
      {"Hyundai i20 N Rally2", "Rally", "WRC2"},
      {"ŠKODA Fabia Rally2 Evo", "Rally", "WRC2"},
      {"ŠKODA Fabia RS Rally2", "Rally", "WRC2"},
      {"Volkswagen Polo GTI R5", "Rally", "WRC2"},
      {"Ford Fiesta Rally3", "Rally", "JUNIOR WRC"},
      {"Ford Fiesta WRC", "Rally", "WORLD RALLY CAR: 2017-2021"},
      {"Volkswagen Polo 2017", "Rally", "WORLD RALLY CAR: 2017-2021"},
      {"Citroën C4 WRC", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Citroën Xsara WRC", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Ford Focus RS Rally 2001", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Ford Focus RS Rally 2008", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"MINI Countryman Rally Edition", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Mitsubishi Lancer Evolution VI", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Peugeot 206 Rally", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Seat Córdoba WRC", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"ŠKODA Fabia WRC", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"SUBARU Impreza 1998", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"SUBARU Impreza 2001", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"SUBARU Impreza 2008", "Rally", "WORLD RALLY CAR: 1997-2011"},
      {"Ford Fiesta R5 MK7 Evo 2", "Rally", "RALLY2"},
      {"Peugeot 208 T16 R5", "Rally", "RALLY2"},
      {"Ford Fiesta MK8 Rally4", "Rally", "RALLY4"},
      {"Opel Adam R2", "Rally", "RALLY4"},
      {"Peugeot 208 Rally4", "Rally", "RALLY4"},
      {"Renault Twingo II", "Rally", "RALLY4"},
      {"McRae R4", "Rally", "NR4/R4"},
      {"Mitsubishi Lancer Evolution X", "Rally", "NR4/R4"},
      {"SUBARU WRX STI NR4", "Rally", "NR4/R4"},
      {"Fiat Grande Punto Abarth S2000", "Rally", "S2000"},
      {"Opel Corsa S2000", "Rally", "S2000"},
      {"Peugeot 207 S2000", "Rally", "S2000"},
      {"Citroën C2 Super 1600", "Rally", "S1600"},
      {"Citroën Saxo Super 1600", "Rally", "S1600"},
      {"Ford Puma S1600", "Rally", "S1600"},
      {"Renault Clio S1600", "Rally", "S1600"},
      {"Ford Escort Mk 6 Maxi", "Rally", "F2 KIT CAR"},
      {"Peugeot 306 Maxi", "Rally", "F2 KIT CAR"},
      {"Renault Maxi Mégane", "Rally", "F2 KIT CAR"},
      {"Seat Ibiza Kit Car", "Rally", "F2 KIT CAR"},
      {"Vauxhall Astra Rally Car", "Rally", "F2 KIT CAR"},
      {"Volkswagen Golf IV Kit Car", "Rally", "F2 KIT CAR"},
      {"Ford Escort RS Cosworth", "Rally", "GROUP A"},
      {"Lancia Delta HF Integrale", "Rally", "GROUP A"},
      {"Mitsubishi Galant VR4", "Rally", "GROUP A"},
      {"SUBARU Impreza 1995", "Rally", "GROUP A"},
      {"SUBARU Legacy RS", "Rally", "GROUP A"},
      {"Audi Sport quattro S1 (E2)", "Rally", "GROUP B (4WD)"},
      {"Ford RS200", "Rally", "GROUP B (4WD)"},
      {"Lancia Delta S4", "Rally", "GROUP B (4WD)"},
      {"MG Metro 6R4", "Rally", "GROUP B (4WD)"},
      {"Peugeot 205 T16 Evo 2", "Rally", "GROUP B (4WD)"},
      {"BMW M1 Procar Rally", "Rally", "GROUP B (RWD)"},
      {"Lancia 037 Evo 2", "Rally", "GROUP B (RWD)"},
      {"Opel Manta 400", "Rally", "GROUP B (RWD)"},
      {"Porsche 911 SC RS", "Rally", "GROUP B (RWD)"},
      {"BMW M3 Evo Rally", "Rally", "H3 (RWD)"},
      {"Ford Escort MK2 McRae Motorsport", "Rally", "H3 (RWD)"},
      {"Ford Sierra Cosworth RS500", "Rally", "H3 (RWD)"},
      {"Lancia Stratos", "Rally", "H3 (RWD)"},
      {"Opel Ascona 400", "Rally", "H3 (RWD)"},
      {"Renault 5 Turbo", "Rally", "H3 (RWD)"},
      {"Alpine Renault A110 1600 S", "Rally", "H2 (RWD)"},
      {"Fiat 131 Abarth Rally", "Rally", "H2 (RWD)"},
      {"Ford Escort MK2", "Rally", "H2 (RWD)"},
      {"Hillman Avenger", "Rally", "H2 (RWD)"},
      {"Opel Kadett C GT/E", "Rally", "H2 (RWD)"},
      {"Talbot Sunbeam Lotus", "Rally", "H2 (RWD)"},
      {"Peugeot 205 GTI", "Rally", "H2 (FWD)"},
      {"Peugeot 309 GTI", "Rally", "H2 (FWD)"},
      {"Volkswagen Golf GTI", "Rally", "H2 (FWD)"},
      {"Lancia Fulvia HF", "Rally", "H1 (FWD)"},
      {"MINI Cooper S", "Rally", "H1 (FWD)"},
      {"Vauxhall Nova Sport", "Rally", "H1 (FWD)"},
      {"WRC Builder Car", "Rally", "BUILDER CARS"},
      {"WRC2 Builder Car", "Rally", "BUILDER CARS"},
      {"Junior WRC Builder Car", "Rally", "BUILDER CARS"}
    ]

    circuits_raw = [
      {"Poland", "Poland", "Swietajno", "18.5", "Medium Gravel = 25% Asphalt = 10%"},
      {"Poland", "Poland", "Jelonek", "18.1", "Medium Gravel = 25% Asphalt = 10%"},
      {"Poland", "Poland", "Gajrowskie", "10", "Medium Gravel = 20% Asphalt = 20%"},
      {"Poland", "Poland", "Pietrasze", "9.7", "Medium Gravel = 20% Asphalt = 20%"},
      {"Poland", "Poland", "Dybowo", "8.5", "Medium Gravel = 25% Asphalt = 10%"},
      {"Poland", "Poland", "Chelchy", "8.5", "Medium Gravel = 25% Asphalt = 10%"},
      {"Poland", "Poland", "Mikolajki", "9.4", "Medium Gravel = 25% Asphalt = 5%"},
      {"Poland", "Poland", "Zawada", "9.5", "Medium Gravel = 25% Asphalt = 5%"},
      {"Poland", "Poland", "Gmina Mragowo", "4.4", "Medium Gravel = 30% Asphalt = 5%"},
      {"Poland", "Poland", "Czerwonki", "4.5", "Medium Gravel = 30% Asphalt = 5%"},
      {"Poland", "Poland", "Kosewo", "4.8", "Medium Gravel = 20%"},
      {"Poland", "Poland", "Probark", "4.6", "Medium Gravel = 20%"},
      {"Latvia", "Latvia", "Vecpils", "16.3",
       "Light Gravel = 65% Medium Gravel = 25% Heavy Gravel = 10%"},
      {"Latvia", "Latvia", "Kagene", "16.3",
       "Light Gravel = 65% Medium Gravel = 25% Heavy Gravel = 10%"},
      {"Latvia", "Latvia", "Mazilmaja", "8.5",
       "Light Gravel = 40% Medium Gravel = 40% Heavy Gravel = 20%"},
      {"Latvia", "Latvia", "Kirsits", "8.4",
       "Light Gravel = 40% Medium Gravel = 40% Heavy Gravel = 20%"},
      {"Latvia", "Latvia", "Baznica", "7.6", "Light Gravel = 95% Medium Gravel = 5%"},
      {"Latvia", "Latvia", "Strokacs", "7.7", "Light Gravel = 95% Medium Gravel = 5%"},
      {"Latvia", "Latvia", "Podnieki", "9.9",
       "Light Gravel = 65% Medium Gravel = 20% Heavy Gravel = 15%"},
      {"Latvia", "Latvia", "Dinsdurbe", "9.9",
       "Light Gravel = 65% Medium Gravel = 20% Heavy Gravel = 15%"},
      {"Latvia", "Latvia", "Kalvene", "4.9", "Medium Gravel = 20%"},
      {"Latvia", "Latvia", "Cerpi", "4.9", "Medium Gravel = 20%"},
      {"Latvia", "Latvia", "Krote", "4.9", "Medium Gravel = 20% Heavy Gravel = 20%"},
      {"Latvia", "Latvia", "Kaleti", "5", "Medium Gravel = 25% He/snowavy Gravel = 20%"},
      {"Monaco", "Monte Carlo", "La Bollène-Vésubie - Peïra Cava", "18.51", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Peïra Cava - La Bollène-Vésubie", "18.18", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "La Bollène-Vésubie - Col de Turini", "9.21", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Pra d'Alart", "8.88", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "La Maïris", "9.3", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Baisse de Patronel", "9.3", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Saint-Léger-les-Mélèzes - La Bâtie-Neuve", "16.79",
       "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "La Bâtie-Neuve - Saint-Léger-les-Mélèzes", "16.64",
       "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Moissière", "8.18", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Ancelle", "8.03", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Ravin de Coste Belle", "8.6", "Asphalt = 100%"},
      {"Monaco", "Monte Carlo", "Les Borels", "8.6", "Asphalt = 100%"},
      {"Sweden", "Sweden", "Hof-Finnskog", "21.47", "Snow = 100%"},
      {"Sweden", "Sweden", "Åsnes", "21.46", "Snow = 100%"},
      {"Sweden", "Sweden", "Spikbrenna", "11.07", "Snow = 100%"},
      {"Sweden", "Sweden", "Lauksjøen", "10.95", "Snow = 100%"},
      {"Sweden", "Sweden", "Åslia", "10.39", "Snow = 100%"},
      {"Sweden", "Sweden", "Knapptjernet", "10.51", "Snow = 100%"},
      {"Sweden", "Sweden", "Vargasen", "8.24", "Snow = 100%"},
      {"Sweden", "Sweden", "Lövstaholm", "8.24", "Snow = 100%"},
      {"Sweden", "Sweden", "Älgsjön", "3.37", "Snow = 100%"},
      {"Sweden", "Sweden", "Ekshärad", "3.37", "Snow = 100%"},
      {"Sweden", "Sweden", "Stora Jangen", "4.86", "Snow = 100%"},
      {"Sweden", "Sweden", "Sunne", "4.86", "Snow = 100%"},
      {"Chile", "Guanajuato", "El Chocolate", "26.68", "Gravel = 92% Dirt = 5% Asphalt = 3%"},
      {"Chile", "Guanajuato", "Otates", "24.74", "Gravel = 92% Dirt = 5% Asphalt = 3%"},
      {"Chile", "Guanajuato", "Ortega", "13.1", "Gravel = 91% Dirt = 7% Asphalt = 2%"},
      {"Chile", "Guanajuato", "Las Minas", "11.46", "Gravel = 92% Dirt = 6% Asphalt = 2%"},
      {"Chile", "Guanajuato", "Ibarrilla", "12.92", "Gravel = 94% Sand = 2% Asphalt = 4%"},
      {"Chile", "Guanajuato", "Derramadero", "7.18", "Gravel = 88% Dirt = 9% Asphalt = 3%"},
      {"Chile", "Guanajuato", "El Brinco", "10.51", "Gravel = 92% Dirt = 6% Asphalt = 2%"},
      {"Chile", "Guanajuato", "Guanajuatito", "10.62", "Gravel = 89% Dirt = 6% Asphalt = 5%"},
      {"Chile", "Guanajuato", "Alfaro", "8", "Gravel = 92% Sand = 4% Asphalt = 4%"},
      {"Chile", "Guanajuato", "Mesa Cuata", "8.8", "Gravel = 90% Sand = 3% Asphalt = 7%"},
      {"Chile", "Guanajuato", "San Diego", "5.78", "Gravel = 98% Dirt = 1% Sand = 1%"},
      {"Chile", "Guanajuato", "El Mosquito", "6.84", "Gravel = 97% Dirt = 1% Sand = 2%"},
      {"Croatia", "Croatia", "Bliznec", "25.56", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Trakošćan", "25.56", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Vrbno", "12.7", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Zagorska Sela", "12.7", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Kumrovec", "12.94", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Grdanjci", "12.86", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Stojdraga", "10.24", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Mali Lipovec", "10.24", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Hartje", "7.79", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Kostanjevac", "8.7", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Krašić", "8.77", "Asphalt = 100%"},
      {"Croatia", "Croatia", "Petruš Vrh", "8.77", "Asphalt = 100%"},
      {"Portugal", "Portugal", "Baião", "30.32", "Gravel = 82% Asphalt = 16% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Caminha", "31.21", "Gravel = 79% Asphalt = 19% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Fridão", "16.72", "Gravel = 88% Asphalt = 10% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Marão", "15.12", "Gravel = 68% Asphalt = 30% Cobblestone =2%"},
      {"Portugal", "Portugal", "Ponte de Lima", "14.77",
       "Gravel = 69% Asphalt = 29% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Viana do Castelo", "7.87",
       "Gravel = 95% Asphalt = 2% Cobblestone = 3%"},
      {"Portugal", "Portugal", "Ervideiro", "7.3", "Gravel = 96% Asphalt = 2% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Celeiro", "8.18", "Gravel = 96% Asphalt = 2% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Touca", "7.51", "Gravel = 92% Asphalt = 6% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Vila Boa", "7.39", "Gravel = 72% Asphalt = 26% Cobblestone = 2%"},
      {"Portugal", "Portugal", "Carrazedo", "7.48",
       "Gravel = 75% Asphalt = 22% Cobblestone = 3%"},
      {"Portugal", "Portugal", "Anjos", "7.39", "Gravel = 65% Asphalt = 35%"},
      {"Italy", "Sardinia", "Rena Majore", "31.53", "Gravel = 82% Sand = 14% Asphalt = 4%"},
      {"Italy", "Sardinia", "Monte Olia", "31.62", "Gravel = 82% Sand = 14% Asphalt = 4%"},
      {"Italy", "Sardinia", "Littichedda", "13.3", "Gravel = 68% Sand = 23% Asphalt =9%"},
      {"Italy", "Sardinia", "Ala del Sardi", "18.22", "Gravel = 92% Sand = 1% Asphalt = 7%"},
      {"Italy", "Sardinia", "Mamone", "16.45", "Gravel = 96% Asphalt = 4%"},
      {"Italy", "Sardinia", "Li Pinnenti", "7.6", "Gravel = 59% Sand = 40% Asphalt = 1%"},
      {"Italy", "Sardinia", "Malti", "7.73", "Gravel = 57% Sand = 39% Asphalt = 4%"},
      {"Italy", "Sardinia", "Bassacutena", "7.49", "Gravel = 71% Sand = 16% Asphalt = 13%"},
      {"Italy", "Sardinia", "Bortigiadas", "9.02", "Gravel = 94% Asphalt = 6%"},
      {"Italy", "Sardinia", "Sa Mela", "9.13", "Gravel = 100%"},
      {"Italy", "Sardinia", "Monte Muvri", "7.51", "Gravel = 100%"},
      {"Italy", "Sardinia", "Monte Acuto", "7.44", "Gravel = 100%"},
      {"Kenya", "Kenya", "Malewa", "9.7", "Gravel = 82% Rock = 14% Dirt = 4%"},
      {"Kenya", "Kenya", "Tarambete", "9.63", "Gravel = 82% Rock = 14% Dirt = 4%"},
      {"Kenya", "Kenya", "Moi North", "5.46", "Gravel = 83% Rock = 12% Dirt = 5%"},
      {"Kenya", "Kenya", "Marula", "5.48", "Gravel = 82% Rock = 13% Dirt = 5%"},
      {"Kenya", "Kenya", "Wileli", "4.92", "Gravel = 85% Rock = 12% Dirt = 3%"},
      {"Kenya", "Kenya", "Kingono", "4.41", "Gravel = 82% Rock = 12% Dirt = 3%"},
      {"Kenya", "Kenya", "Soysambu", "20.67", "Gravel = 51% Sand = 35% Dirt = 14%"},
      {"Kenya", "Kenya", "Mbaruk", "20.23", "Gravel = 50% Sand = 36% Dirt = 14%"},
      {"Kenya", "Kenya", "Sugunoi", "9.74", "Gravel = 32% Sand = 54% Dirt = 14%"},
      {"Kenya", "Kenya", "Nakuru", "9.98", "Gravel = 33% Sand = 53% Dirt = 14%"},
      {"Kenya", "Kenya", "Kanyawa", "10.7", "Gravel = 64% Sand = 21% Dirt = 15%"},
      {"Kenya", "Kenya", "Kanyawa - Nakura", "10.69", "Gravel = 64% Sand = 20% Dirt = 16%"},
      {"Estonia", "Estonia", "Otepää", "17.07", "Gravel = 88% Dirt = 12%"},
      {"Estonia", "Estonia", "Rebaste", "17.07", "Gravel = 88% Dirt = 12%"},
      {"Estonia", "Estonia", "Nüpli", "8.6", "Gravel = 91% Dirt = 9%"},
      {"Estonia", "Estonia", "Truuta", "8.6", "Gravel = 91% Dirt = 9%"},
      {"Estonia", "Estonia", "Koigu", "8.47", "Gravel = 82% Dirt = 18%"},
      {"Estonia", "Estonia", "Kooraste", "8.47", "Gravel = 82% Dirt = 18%"},
      {"Estonia", "Estonia", "Elva", "11.82", "Gravel = 80% Asphalt = 11% Dirt = 9%"},
      {"Estonia", "Estonia", "Metsalaane", "11.56", "Gravel = 80% Asphalt = 11% Dirt = 9%"},
      {"Estonia", "Estonia", "Vahessaare", "6.17", "Gravel = 81% Asphalt = 8% Dirt = 11%"},
      {"Estonia", "Estonia", "Külaaseme", "6.17", "Gravel = 80% Asphalt = 8% Dirt = 12%"},
      {"Estonia", "Estonia", "Vissi", "5.63", "Gravel = 78% Asphalt = 13% Dirt = 9%"},
      {"Estonia", "Estonia", "Vellavere", "5.63", "Gravel = 79% Asphalt = 13% Dirt = 8%"},
      {"Finland", "Finland", "Leustu", "11.09", "Gravel = 100%"},
      {"Finland", "Finland", "Lahdenkyla", "11", "Gravel = 100%"},
      {"Finland", "Finland", "Saakoski", "4.83", "Gravel = 100%"},
      {"Finland", "Finland", "Maahi", "4.73", "Gravel = 100%"},
      {"Finland", "Finland", "Painaa", "6.41", "Gravel = 100%"},
      {"Finland", "Finland", "Peltola", "6.14", "Gravel = 100%"},
      {"Finland", "Finland", "Paijala", "22.92", "Gravel = 100%"},
      {"Finland", "Finland", "Ruokolahti", "22.9", "Gravel = 100%"},
      {"Finland", "Finland", "Honkanen", "10.41", "Gravel = 100%"},
      {"Finland", "Finland", "Venkajarvi", "10.35", "Gravel = 100%"},
      {"Finland", "Finland", "Vehmas", "12.57", "Gravel = 100%"},
      {"Finland", "Finland", "Hatanpaa", "12.5", "Gravel = 100%"},
      {"Greece", "Greece", "Gravia", "24.64", "Dirt = 80% Gravel = 20%"},
      {"Greece", "Greece", "Prosilio", "24.64", "Dirt = 80% Gravel = 20%"},
      {"Greece", "Greece", "Mariolata", "13.51", "Dirt = 64% Gravel = 36%"},
      {"Greece", "Greece", "Karoutes", "13.51", "Dirt = 64% Gravel = 36%"},
      {"Greece", "Greece", "Viniani", "11.12", "Dirt = 100%"},
      {"Greece", "Greece", "Delphi", "11.12", "Dirt = 100%"},
      {"Greece", "Greece", "Eptalofos", "10.39", "Dirt = 80% Gravel = 20%"},
      {"Greece", "Greece", "Lilea", "10.39", "Dirt = 80% Gravel = 20%"},
      {"Greece", "Greece", "Parnassós", "5.57", "Dirt = 46% Gravel = 54%"},
      {"Greece", "Greece", "Bauxites", "5.57", "Dirt = 46% Gravel = 54%"},
      {"Greece", "Greece", "Drosochori", "8.68", "Dirt = 100%"},
      {"Greece", "Greece", "Amfissa", "8.68", "Dirt = 100%"},
      {"Chile", "Bio Bío", "Bio Bío", "34.72", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Arauco", "34.79", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Coronel", "17.97", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Lota", "16.73", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Santa Juana", "16.87", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Los Angeles", "10.79", "Gravel = 100%"},
      {"Chile", "Bio Bío", "San Rosendo", "10.08", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Laja", "7.87", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Yumbel", "7.75", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Florida", "8.21", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Hualqui", "8.09", "Gravel = 100%"},
      {"Chile", "Bio Bío", "Reputo", "8.53", "Gravel = 100%"},
      {"", "Central european", "Rouské", "32.36", "Asphalt = 100%"},
      {"", "Central european", "Lukoveček", "32.34", "Asphalt = 100%"},
      {"", "Central european", "Raztoka", "15.4", "Asphalt = 100%"},
      {"", "Central european", "Žabárna", "15.42", "Asphalt = 100%"},
      {"", "Central european", "Provodovice", "16.99", "Asphalt = 100%"},
      {"", "Central european", "Chvalčov", "16.94", "Asphalt = 100%"},
      {"", "Central european", "Vítová", "8.77", "Asphalt = 100%"},
      {"", "Central european", "Brusné", "0", "Asphalt = 100%"},
      {"", "Central european", "Libosváry", "14.73", "Asphalt = 100%"},
      {"", "Central european", "Rusava", "14.64", "Asphalt = 100%"},
      {"", "Central european", "Osíčko", "8.94", "Asphalt = 100%"},
      {"", "Central european", "Botarell", "8.65", "Asphalt = 100%"},
      {"Japan", "Japan", "Lake Mikawa", "19.89", "Asphalt = 100%"},
      {"Japan", "Japan", "Kudarisawa", "19.88", "Asphalt = 100%"},
      {"Japan", "Japan", "Oninotaira", "11.38", "Asphalt = 100%"},
      {"Japan", "Japan", "Okuwacho", "11.37", "Asphalt = 100%"},
      {"Japan", "Japan", "Habu Dam", "10.27", "Asphalt = 100%"},
      {"Japan", "Japan", "Habucho", "10.28", "Asphalt = 100%"},
      {"Japan", "Japan", "Nenoue Plateau", "13.74", "Asphalt = 100%"},
      {"Japan", "Japan", "Tegano", "13.74", "Asphalt = 100%"},
      {"Japan", "Japan", "Higashino", "6.92", "Asphalt = 100%"},
      {"Japan", "Japan", "Hokono Lake", "6.92", "Asphalt = 100%"},
      {"Japan", "Japan", "Nenoue Highlands", "6.81", "Asphalt = 100%"},
      {"Japan", "Japan", "Moltifao", "6.81", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Asco", "29.2", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Ponte", "28.63", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Monte Cinto", "15.15", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Albarello", "16.16", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Capannace", "20.45", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Serra Di Cuzzioli", "7.66", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Maririe", "8.47", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Poggiola", "8.47", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Monte Alloradu", "10.74", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Ravin de Finelio", "9.46", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Cabanella", "10.09", "Asphalt = 100%"},
      {"Mediterraneo", "Mediterraneo", "Moltifao", "11.17", "Asphalt = 100%"},
      {"", "Pacifico", "Talao", "31.44", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Talanghilirair", "32.4", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "SungaiKunit", "14.58", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Sangir Balai Janggo", "15.53", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "South Solok", "16.87", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Kebun Raya Solok", "8.7", "Gravel = 98% Dirt = 2%"},
      {"", "Pacifico", "Batukangkung", "8.76", "Gravel = 98% Dirt = 2%"},
      {"", "Pacifico", "Abai", "5.37", "Gravel = 98% Dirt = 2%"},
      {"", "Pacifico", "Moearaikoer", "6.34", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Bidaralam", "7.73", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Loeboekmalaka", "7.73", "Gravel = 99% Dirt = 1%"},
      {"", "Pacifico", "Gunung Tujuh", "9.14", "Gravel = 99% Dirt = 1%"},
      {"New Zealand", "Oceania", "Ruakaka", "10.98", "Gravel = 98% Concrete = 2%"},
      {"New Zealand", "Oceania", "Doctors Hill", "10.98", "Gravel = 98% Concrete = 2%"},
      {"New Zealand", "Oceania", "Ahuroa", "6.6", "Gravel = 97% Concrete = 3%"},
      {"New Zealand", "Oceania", "Ahuroa - Waipu", "6.6", "Gravel = 97% Concrete = 3%"},
      {"New Zealand", "Oceania", "Ruakaka - Maungaturoto", "4.37", "Gravel = 100%"},
      {"New Zealand", "Oceania", "Maungaturoto", "4.37", "Gravel = 100%"},
      {"New Zealand", "Oceania", "Waiwera", "18.03", "Gravel = 97% Asphalt = 2% Concrete = 1%"},
      {"New Zealand", "Oceania", "Tahekeroa", "18.02", "Gravel = 97% Asphalt = 2% Concrete = 1%"},
      {"New Zealand", "Oceania", "Noakes Hill", "0", "Gravel = 98% Asphalt = 2%"},
      {"New Zealand", "Oceania", "Orewa", "0", "Gravel = 98% Asphalt = 2%"},
      {"New Zealand", "Oceania", "Tahekeroa - Orewa", "0", "Gravel = 99% Asphalt = 1%"},
      {"New Zealand", "Oceania", "Makarau", "0", "Gravel = 99% Asphalt = 1%"},
      {"", "Scandia", "Holtjønn", "30.93", "Snow = 99% Ice = 1%"},
      {"", "Scandia", "Hengeltjønn", "31.84", "Snow = 99% Ice = 1%"},
      {"", "Scandia", "Fyresvatn", "17.1", "Snow = 100%"},
      {"", "Scandia", "Russvatn", "16.79", "Snow = 100%"},
      {"", "Scandia", "Tovsli", "13.75", "Snow = 100%"},
      {"", "Scandia", "Kottjønn", "6.62", "Snow = 100%"},
      {"", "Scandia", "Fordol", "5.43", "Snow = 100%"},
      {"", "Scandia", "Fyresdal", "5.43", "Snow = 100%"},
      {"", "Scandia", "Ljosdalstjønn", "9.37", "Snow = 100%"},
      {"", "Scandia", "Dagtrolltjønn", "9.27", "Snow = 100%"},
      {"", "Scandia", "Tovslioytjorn", "7.52", "Snow = 100%"},
      {"", "Scandia", "Bergsøytjønn", "7.29", "Snow = 100%"},
      {"", "Iberia", "Santes Creus", "18.98", "Asphalt = 94% Concrete = 6%"},
      {"", "Iberia", "La Llacuna", "18.98", "Asphalt = 94% Concrete = 6%"},
      {"", "Iberia", "Seguer", "9.74", "Asphalt = 94% Concrete = 6%"},
      {"", "Iberia", "Esblada", "9.74", "Asphalt = 94% Concrete = 6%"},
      {"", "Iberia", "Montagut", "9.24", "Asphalt = 95% Concrete = 5%"},
      {"", "Iberia", "Aiguamúrcia", "9.24", "Asphalt = 95% Concrete = 5%"},
      {"", "Iberia", "Alforja", "16.28", "Asphalt = 100%"},
      {"", "Iberia", "Les Irles", "16.28", "Asphalt = 100%"},
      {"", "Iberia", "Duesaigües", "8.94", "Asphalt = 100%"},
      {"", "Iberia", "Les Voltes", "8.94", "Asphalt = 100%"},
      {"", "Iberia", "Montclar", "7.33", "Asphalt = 100%"},
      {"", "Iberia", "Botarell", "7.33", "Asphalt = 100%"}
    ]

    circuits =
      circuits_raw
      |> Enum.map(fn {country, region, name, distance_string, surface} ->
        {distance, ""} = Float.parse(distance_string)

        %{
          game_id: game.id,
          country: country,
          region: region,
          name: name,
          distance: distance,
          surface: surface,
          inserted_at: now,
          updated_at: now
        }
      end)

    Ecto.Multi.new()
    |> Ecto.Multi.insert_all(:insert_all_wrc_24_circuits, Circuit, circuits)
    |> Repo.transaction()

    cars =
      cars_raw
      |> Enum.map(fn {name, class, sub_class} ->
        %{
          game_id: game.id,
          name: name,
          class: class,
          sub_class: sub_class,
          inserted_at: now,
          updated_at: now
        }
      end)

    Ecto.Multi.new()
    |> Ecto.Multi.insert_all(:insert_all_wrc_24_cars, Car, cars)
    |> Repo.transaction()
  end

  def down do
    game = Games.get_game_by_code!("wrc-24")
    circuits = from(c in Circuit, where: c.game_id == ^game.id)

    Ecto.Multi.new()
    |> Ecto.Multi.delete_all(:delete_all_wrc_24_circuits, circuits)
    |> Repo.transaction()

    cars = from(c in Car, where: c.game_id == ^game.id)

    Ecto.Multi.new()
    |> Ecto.Multi.delete_all(:delete_all_wrc_24_cars, cars)
    |> Repo.transaction()
  end
end
